### ISSUE TITLE
Some trouble with the program

### ISSUE THREAD

**Issue by georgeokelly** [kyo055/ncnn_yolo2#1]
Hi, I‘m trying with your project and now I get some trouble with it.

When I open the `tensor_model.sln` there's an error that the `tensor_model.vcxproj` is missing.

And in fact I don't know whether it's the first step I should do to run this project. Is it necessary?

Could you provide with a more detailed introduction and I would appreciate it very much.

**Comment by kyo055** [comment]
Hi, because I'm a lazy man, the `tensor_model` is another project about liveness_detection. When I upload just ignore it. This project have nothing to do with the `tensor_mdoel.vcxproj`, and I think you should modify the `project properties` as follows:

> I have to say this project just support the release

### 1. modify include directory and lib directory     
![image](https://note.youdao.com/yws/api/personal/file/ED1CCFCD5172422FB4E740154E41E441?method=download&shareKey=b12f40d571e93a75b549f76614674399)    

### 2. add the command line arguments    
![image](https://note.youdao.com/yws/api/personal/file/1562057095CA49E6B8F8DB843233C6B7?method=download&shareKey=7254d2326a894cf9d30f23e7ad3d5e28)   

### 3. add the `opencv` and the `ncnn` target link
> I think this step you can skip, and this prop is already in the solution.
![image](https://note.youdao.com/yws/api/personal/file/2C38A9D54BCC41D1BBDC915F9D8DB6CD?method=download&shareKey=01c9e1079da07c0e26b46a7283c3d831)

### 4. build the project
If you set the command line 's', the result will be like this.
![image](https://note.youdao.com/yws/api/personal/file/990208055D464AC58B2BBF587E0F0576?method=download&shareKey=c1fed6a5f88599ce9b3b66e6d80ef67f)

**Comment by georgeokelly** [comment]
谢谢。现在项目可以成功运行，不过图片没显示出来。
![tim 20180502140402](https://user-images.githubusercontent.com/34239051/39507721-e46c2b3a-4e11-11e8-8d19-10aad67a9dea.png)

另外我在尝试linux平台的pytorch yolo转ncnn，不过遇到一个问题：直接运行run.py的时候（默认转换的是FaceBoxes）它了这个错误：
```
FaceBoxes
Saving default weight initialization...
Converting...
Traceback (most recent call last):
  File "run.py", line 101, in <module>
    text_net, binary_weights = ConvertModel_ncnn(pytorch_net, InputShape, softmax=False)
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 327, in ConvertModel_ncnn
    DFS(out.grad_fn)
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 85, in DFS
    child_name = DFS(u[0])
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 85, in DFS
    child_name = DFS(u[0])
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 85, in DFS
    child_name = DFS(u[0])
  [Previous line repeated 22 more times]
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 160, in DFS
    layer = convert('', layer_type_name, func)
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertLayer_ncnn.py", line 469, in convert_ncnn
    typename, converter.keys()))
ValueError: Unknown layer type: ThnnConv2D, known types: dict_keys(['data', 'Addmm', 'Threshold', 'ConvNd', 'MaxPool2d', 'AvgPool2d', 'Add', 'Cmax', 'BatchNorm', 'Concat', 'Dro
pout', 'UpsamplingBilinear2d', 'MulConstant', 'AddConstant', 'Softmax', 'Sigmoid', 'Tanh', 'ELU', 'LeakyReLU', 'PReLU', 'Slice', 'MultiCopy', 'Negate', 'Permute', 'View'])
```
然后我尝试转换Yolo，也是这个报错。想问问您如何解决呢？
